version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/ruby
        auth:
          username: ryohei1000000000@gmail.com
          password: 38ryohei38

jobs:
  build:
    executor:
      name: my-executor
    steps:
      - run: echo Hello World
