version2
jobs:
  build:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: テストファイル分割1
          command: |
            circleci tests glob "__tests__/*.ts" | \
            circlrci tests split --total=2 --index=0
      - run:
          name: テストファイル分割2
          command: |
            circleci tests glob "__tests__/*.ts" | \
            circlrci tests split --total=2 --index=1
