version: 2.1
commands:
  sayhello:
    description: "Say Hello"
    parameters:
      to:
        type: string
        default: "TEST"
    steps:
      - run: echo Hello World

executors:
  my-executor:
    docker:
      - image: cimg/ruby:3.0.4-node
jobs:
  build:
    executor:
      name: my-executor
    steps:
      - sayhello:
          to: "TTTTT"
