version: 2.1
executors:
  my-executor:
    docker:
      - image: cimg/ruby-2.7.1-node
      - auth:
        username: ryohei1216
        password: 38ryohei38
jobs:
  build:
    executor:
      name: my-executor
    steps:
      - run: echo Hello World
