executors:
  wih_db:
    docker:
      - image: cimg/ruby:3.0.4
        environment:
          DB_HOST: 127.0.0.1
          RAILS_ENV: test
      - image: circleci/mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ""
          MYSQL_DATABASE: dbserver01
        command: mysql --default-authentication-plugin=mysql_native_password
    working_directory: ~/repo

version: 2.1
jobs:
  setup:
    executor: wih_db
    steps:
      - checkout
      - run:
          name: gemのインストール
          command: bundle install
      - run:
          name: DB起動を待機
          command: |
            dockerize -wait \
            tcp://${DB_HOST}:3306 -timeout 120s
      - run:
          name: DBセットアップ
          command: bundle exec rspec

workflows:
  version: 2
  build-test:
    jobs:
      - setup
