version: 2.1

executors:
  default:
    docker:
      - image: cimg/node:lts
    working_directory: ~/repo
jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Nodeモジュールのインストール
          command: yarn install
      - persist_to_workspace:
          root: ~/repo
          path:
            - node_modules

  test-jest:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Jestを実行
          command: npx jest --ci --maxWorker=2

workflows:
  version: 2
  build-test:
    jobs:
      - setup
      - test-jest:
          requires:
            - setup
